version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chichia
      POSTGRES_DB: dairyWorks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: chichia/dairy:latest
    container_name: my_dairy
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL:-jdbc:postgresql://postgres:5432/dairyWorks}
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: chichia
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
